run:
  timeout: 5m
  output-format: colored-line-number

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - revive
    - gocritic

issues:
  exclude-use-default: false 