run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - deadcode
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - revive
    - gocritic

issues:
  exclude-use-default: false 